FROM golang:1.23-alpine AS builder
RUN apk update && apk add --no-cache gcc musl-dev
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=1 GOOS=linux go build -a -o orchestrator ./cmd/orchestrator/main.go
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/orchestrator .
EXPOSE 8080
ENTRYPOINT ["./orchestrator"]